### ISSUE TITLE
can't get `open-sans` font

### ISSUE THREAD

**Issue by Pkcarreno** [obytes/app-icon-badge#23]
For some reason, when building a clean project from the obytes template, it throws an error related to not getting the font

```powershell

[Error: ENOENT: no such file or directory, open 'C:\Users\pedro\Churup\android\fonts\open-sans\open-sans-128-white\open-sans-128-white.fnt'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\pedro\\Churup\\android\\fonts\\open-sans\\open-sans-128-white\\open-sans-128-white.fnt'
}

```

I have not been able to do an individual test of this library yet. The only proof I have is in the [`utils.ts`](https://github.com/obytes/app-icon-badge/blob/master/utils.ts) file, this same font is mentioned:

```typescript

export const getFont = (isAdaptiveIcon: Boolean, isFontBlack: Boolean) =>
  isAdaptiveIcon
    ? isFontBlack
      ? Jimp.FONT_SANS_64_BLACK
      : Jimp.FONT_SANS_64_WHITE
    : isFontBlack
    ? Jimp.FONT_SANS_128_BLACK
    : Jimp.FONT_SANS_128_WHITE;

```

Also, it is the only major difference in the latest version of the template against the previous one (which works correctly).

It is worth mentioning that inside the `android` folder in the root of the project there is no `fonts` folder so in effect it does not get the font when building. Shouldn't this font be looked for inside the library folder instead of the root of the project? or is it generated during the build? or should I manually import this font into the android folder? I don't see the latter mentioned in the readme.

For more details [read this issue](https://github.com/obytes/react-native-template-obytes/issues/174)

**Comment by SihamBen** [comment]
@Pkcarreno Thank you for reporting the issue, we have released a new version with a fix. Can you please try and let us know if you have faced any other issues, or create a PR if you have any suggested solutions

**Comment by SihamBen** [comment]
@Pkcarreno Thank you for reporting the issue, we have released a new version with a fix. Can you please try and let us know if you have faced any other issues, or create a PR if you have any suggested solutions
