### ISSUE TITLE
Wired error occurred while running `pnpm android`.

### ISSUE THREAD

**Issue by yjose** [obytes/app-icon-badge#25]
While running the plugin with the template, I noticed that the plugin works as expected when running `pnpm prebuild`, but it throws an error when running `pnpm android`. This error does not break the build but shows the following error:

```
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: ENOENT: no such file or directory, open './assets/icon.png'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './assets/icon.png',
  methodName: 'constructor'
}
```

**Comment by 0x10Ayoub** [comment]
this is  because when the plugin runs on build phase,  nodejs use android/ios as a root and there's no  ` ./android|ios/assets`

**Comment by yjose** [comment]
> this is  because when the plugin runs on build phase,  nodejs use android/ios as a root and there's no  ` ./android|ios/assets`

Any idea how we can fix in the plugin level?

**Comment by 0x10Ayoub** [comment]
I'm not aware if there's a way that expo can let us know in which cycle the plugin runs my solution 
- environment variable
- or just make sure the file exist before we run code

**Comment by yjose** [comment]
I believe the second option is much better. Alternatively, adding a try-catch block for the plugin could prevent the error.
